version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Zipping deployment package...
      - zip -r deployment.zip .
artifacts:
  files:
    - deployment.zip

