version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.24
  build:
    commands:
      - echo Build started on `date`
      - echo Initializing Go modules and downloading dependencies...
      - go mod init main
      - go mod tidy
      - echo Compiling the Go code...
      - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o bootstrap main.go
      - echo Zipping the binary...
      - zip deployment.zip bootstrap
artifacts:
  files:
    - deployment.zip

