version: 0.2

phases:
  install:
    runtime-versions:
      # chromedpの依存関係が要求するGo 1.24を指定します。
      golang: 1.24
  build:
    commands:
      - echo Build started on `date`
      - echo Initializing Go modules and downloading dependencies...
      # Goモジュールを初期化し、main.goでimportされているライブラリをダウンロードします。
      - go mod init main
      - go mod tidy
      - echo Compiling the Go code...
      # GoプログラムをLambdaで実行可能な形式にビルドします。
      - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o bootstrap main.go
      - echo Zipping the binary...
      # ビルドした実行可能ファイルをZIP形式に圧縮します。
      - zip deployment.zip bootstrap

# ビルド成果物としてdeployment.zipを指定します。
artifacts:
  files:
    - deployment.zip

