version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Go code...
      # GoプログラムをLambdaで実行可能な形式にビルドします。
      - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o bootstrap main.go
      - echo Zipping the binary...
      # ビルドした実行可能ファイルをZIP形式に圧縮します。
      - zip deployment.zip bootstrap

# ビルド成果物としてdeployment.zipを指定します。
artifacts:
  files:
    - deployment.zip

